version: '3.8'
services:
  redis:
    image: redis:7.0.11-alpine
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'fake@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'fakepassword'
    ports:
      - '16543:80'
    depends_on:
      - db
  api:
    container_name: api
    build:
      context: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    links:
      - db
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  db:
    driver: local
